projects:
  confingservice:
    schemaPath: src/graphql/schema.json
    includes:
      - profilequery
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
